package interpreter;

public enum TokenType
{
    NUMBER, NEWLINE, OPERATOR, EOF, UNKNOWN,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, LEFT_PAREN, 
    RIGHT_PAREN, LESS, GREATER, EQUAL, NOTEQUAL,
    LESSEQUAL, GREATEREQUAL, ASSIGNMENT, NOT, OR, AND,
    STRING, KEYWORD, PRINT, PRINTLN, WAIT, END, SCRIPT,
    WHILE, IF, ELSE, LEFT_BRACKET, RIGHT_BRACKET, COMMA,
    DEF
}